--- #YAML:1.0
name:               Crypt-NSS
version:            0.04
abstract:           Perl bindings to NSS (Netscape Security Services)
author:
    - Claes Jakobsson <claesjac@cpan.org>
license:            mit
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    Socket:           0
    Symbol:           0
    Test::Exception:  0
    Test::More:       0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.46
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
